# Generated by Django 3.0.8 on 2020-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('opening', models.FloatField()),
                ('closing', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
